export enum EVENT_TYPE {
  THREE = 'THREE',
  CONTROL = 'CONTROL'
}

export enum THREE_EVENT_TYPE {
  OBJECT_SELECTED = 'OBJECT_SELECTED',
  OBJECT_CHANGE = 'OBJECT_CHANGE',
  SCENE_READY = 'SCENE_READY'
}

export enum CONTROL_EVENT_TYPE {
  CAMERA_TYPE = 'CAMERA_TYPE',
  SELECTED_OBJECT_TRANSFORM = 'SELECTED_OBJECT_TRANSFORM'
}
