export enum EVENT_TYPE {
  THREE = 'THREE',
  STANDARD_CONTROL = 'STANDARD_CONTROL',
  CUSTOM_CONTROL = 'CUSTOM_CONTROL',
  SCREEN_INFO = 'SCREEN_INFO'
}

export enum THREE_EVENT_TYPE {
  OBJECT_SELECTED = 'OBJECT_SELECTED',
  SELECTED_OBJECT_TRANSFORM = 'SELECTED_OBJECT_TRANSFORM',
  SCENE_READY = 'SCENE_READY',
  POINTER_MOVE = 'POINTER_MOVE',
  POINTER_CLICK = 'POINTER_CLICK',
  POINTER_DOWN = 'POINTER_DOWN',
  POINTER_UP = 'POINTER_UP',
  OBJECT_HIT = 'OBJECT_HIT',
  SCENE_RESIZE = 'SCENE_RESIZE'
}

export enum STANDARD_CONTROL_EVENT_TYPE {
  CAMERA_TYPE = 'CAMERA_TYPE',
  SELECTED_OBJECT_TRANSFORM = 'SELECTED_OBJECT_TRANSFORM'
}

export enum CUSTOM_CONTROL_EVENT_TYPE {
  CREATE = 'CREATE',
  VALUE_CHANGED = 'VALUE_CHANGED'
}

export enum SCREEN_INFO_EVENT_TYPE {
  CREATE = 'CREATE',
  VALUE_CHANGED = 'VALUE_CHANGED',
  REFRESH_POSITION = 'REFRESH_POSITION'
}
